# Generated by Django 6.1 on 2026-09-06 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('owner', 'name'), name='unique_root_folder_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('owner', 'parent', 'name'), name='unique_child_folder_name_per_owner'),
        ),
    ]
