from django.urls import path

from .views import (
    ActivityLogListAPIView,
    DashboardView,
    FileDetailAPIView,
    FileDetailPageView,
    FileDownloadAPIView,
    FileListAPIView,
    FilePermanentDeleteAPIView,
    FileRestoreAPIView,
    FileShareLinkCreateAPIView,
    FileStarAPIView,
    FileStarPageActionView,
    FileTrashPageActionView,
    FileUnstarAPIView,
    FileUploadAPIView,
    FolderDetailAPIView,
    FolderDetailPageView,
    FolderListCreateAPIView,
    FolderPermanentDeleteAPIView,
    FolderRestoreAPIView,
    FolderTrashPageActionView,
    LoginAPIView,
    LogoutAPIView,
    SharedFileViewAPIView,
    SharedLinksPageView,
    ShareLinkDestroyAPIView,
    ShareLinkListCreateAPIView,
    ShareLinkRevokePageView,
    StaffDashboardPageView,
    StaffActivityLogListAPIView,
    StaffFileSummaryAPIView,
    StaffReportAPIView,
    StaffStorageStatsAPIView,
    StarredPageView,
    TrashPageView,
    TrashListAPIView,
    TrashFolderListAPIView,
)


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("folders/<int:pk>/", FolderDetailPageView.as_view(), name="folder-detail-page"),
    path("files/<int:pk>/", FileDetailPageView.as_view(), name="file-detail-page"),
    path("trash/", TrashPageView.as_view(), name="trash-page"),
    path("starred/", StarredPageView.as_view(), name="starred-page"),
    path("shared-links/", SharedLinksPageView.as_view(), name="shared-links-page"),
    path("staff/", StaffDashboardPageView.as_view(), name="staff-dashboard-page"),
    path(
        "files/<int:pk>/trash/<str:action>/",
        FileTrashPageActionView.as_view(),
        name="file-trash-page-action",
    ),
    path(
        "files/<int:pk>/star/<str:action>/",
        FileStarPageActionView.as_view(),
        name="file-star-page-action",
    ),
    path(
        "folders/<int:pk>/trash/<str:action>/",
        FolderTrashPageActionView.as_view(),
        name="folder-trash-page-action",
    ),
    path(
        "shared-links/<int:pk>/revoke/",
        ShareLinkRevokePageView.as_view(),
        name="share-link-revoke-page",
    ),
    path("api/auth/login/", LoginAPIView.as_view(), name="api-login"),
    path("api/auth/logout/", LogoutAPIView.as_view(), name="api-logout"),
    path(
        "api/activity-logs/",
        ActivityLogListAPIView.as_view(),
        name="activity-log-list",
    ),
    path(
        "api/staff/activity-logs/",
        StaffActivityLogListAPIView.as_view(),
        name="staff-activity-log-list",
    ),
    path(
        "api/staff/reports/",
        StaffReportAPIView.as_view(),
        name="staff-reports",
    ),
    path(
        "api/staff/storage-stats/",
        StaffStorageStatsAPIView.as_view(),
        name="staff-storage-stats",
    ),
    path(
        "api/staff/file-summary/",
        StaffFileSummaryAPIView.as_view(),
        name="staff-file-summary",
    ),
    path(
        "api/folders/",
        FolderListCreateAPIView.as_view(),
        name="folder-list-create",
    ),
    path(
        "api/folders/<int:pk>/",
        FolderDetailAPIView.as_view(),
        name="folder-detail",
    ),
    path(
        "api/folders/<int:pk>/restore/",
        FolderRestoreAPIView.as_view(),
        name="folder-restore",
    ),
    path(
        "api/folders/<int:pk>/permanent/",
        FolderPermanentDeleteAPIView.as_view(),
        name="folder-permanent-delete",
    ),
    path("api/files/", FileListAPIView.as_view(), name="file-list"),
    path("api/files/upload/", FileUploadAPIView.as_view(), name="file-upload"),
    path(
        "api/files/<int:pk>/",
        FileDetailAPIView.as_view(),
        name="file-detail",
    ),
    path(
        "api/files/<int:pk>/restore/",
        FileRestoreAPIView.as_view(),
        name="file-restore",
    ),
    path("api/files/<int:pk>/star/", FileStarAPIView.as_view(), name="file-star"),
    path("api/files/<int:pk>/unstar/", FileUnstarAPIView.as_view(), name="file-unstar"),
    path(
        "api/files/<int:pk>/permanent/",
        FilePermanentDeleteAPIView.as_view(),
        name="file-permanent-delete",
    ),
    path("api/trash/", TrashListAPIView.as_view(), name="trash-list"),
    path("api/trash/files/", TrashListAPIView.as_view(), name="trash-file-list"),
    path(
        "api/trash/folders/",
        TrashFolderListAPIView.as_view(),
        name="trash-folder-list",
    ),
    path(
        "api/trash/files/<int:pk>/restore/",
        FileRestoreAPIView.as_view(),
        name="trash-file-restore",
    ),
    path(
        "api/trash/folders/<int:pk>/restore/",
        FolderRestoreAPIView.as_view(),
        name="trash-folder-restore",
    ),
    path(
        "api/trash/files/<int:pk>/permanent/",
        FilePermanentDeleteAPIView.as_view(),
        name="trash-file-permanent-delete",
    ),
    path(
        "api/trash/folders/<int:pk>/permanent/",
        FolderPermanentDeleteAPIView.as_view(),
        name="trash-folder-permanent-delete",
    ),
    path(
        "api/files/<int:pk>/share-links/",
        FileShareLinkCreateAPIView.as_view(),
        name="file-share-link-create",
    ),
    path(
        "api/share-links/",
        ShareLinkListCreateAPIView.as_view(),
        name="share-link-list-create",
    ),
    path(
        "api/share-links/<int:pk>/",
        ShareLinkDestroyAPIView.as_view(),
        name="share-link-destroy",
    ),
    path(
        "api/files/<int:pk>/view/",
        SharedFileViewAPIView.as_view(),
        name="shared-file-view",
    ),
    path(
        "api/files/<int:pk>/download/",
        FileDownloadAPIView.as_view(),
        name="file-download",
    ),
]
